version: 2.1

commands:
  setup-git:
    steps:
      - run:
          name: Setup Git
          command: |
            git config user.email "cortlan.bainbridge@gmail.com"
            git config user.name "Circle CI"
      - add_ssh_keys

workflows:
  version: 2
  commit:
    jobs:
      - update
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - update

jobs:
  update:
    docker:
      - image: circleci/node:lts
    parallelism: 1
    working_directory: /tmp/workspace
    steps:
      - checkout
      - setup-git
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: echo $GCP_KEY > credentials.json
      - run: rm README.md
      - run: npm start
      - run: npm test
      - run: git add .
      - run: git commit -m '[skip ci] updating recipes'
      - run: git push origin HEAD
