version: 2.1

commands:
  setup-git:
    steps:
      - run:
          name: Setup Git
          command: |
            git config user.email "cortlan.bainbridge@gmail.com"
            git config user.name "Circle CI"
      - add_ssh_keys

workflows:
  version: 2
  commit:
    jobs:
      - update:
          filters:
            branches:
              only:
                - master
      - publish:
          filters:
            branches:
              only:
                - master
          requires:
            - update

jobs:
  update:
    docker:
      - image: circleci/node:lts
    parallelism: 1
    working_directory: /tmp/workspace
    steps:
      - checkout
      - setup-git
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm test
      - run: npm run format
      - run: git add .
      - run: git commit -m 'updating recipes [skip ci]'
      - run: git push
  publish:
    docker:
      - image: circleci/node:lts
    parallelism: 1
    working_directory: /tmp/workspace
    steps:
      - checkout
      - setup-git
      - run: git pull
      - run: npm version patch -m "v%s [skip ci]"
      - run: git push --follow-tags origin HEAD
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > /tmp/workspace/.npmrc
      - run: npm publish --access public
