
name: Node.js CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12
      uses: actions/setup-node@v1
      with:
        node-version: '12'
    - run: npm ci
    - run: echo $GCP_KEY > credentials.json
    - run: pwd
    - run: ls
    - run: npm start
    - run: npm test
